title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The site lists the past and upcaomming tennis events and is updated through public contribution.
baseurl: "/tennis-events" # the subpath of your site, e.g. /blog
url: "http://divyessh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "post"
      categories: jekyll update

pagination:
  enabled: true
  per_page: 50
  debug: true
  permalink: '/:num/'
  category: 'posts'

future: true